[Jigsaw Labs] Update Extractors.yml and Threads Staging
meltano/squared pull request #335
Opened 2022-08-03 01:00 UTC by WayneBanksy

## Jigsaw Labs - PR No.1 

**Goals:**
- Create staging for threads stream
- Update meltano.extractors.yml `selected_channels` list, `start_date`, and **slack streams**'

**Specific Updates:**
- added **stg_slack_threads.sql** to **data/extract/transform/models/staging/slack/**
- updated **data/extract/extractors.meltano.yml**

**Testing**
- [x] successful call to Slack API given updated channels list, start_date and specified streams
- [ ] end-to-end testing against existing squared repo pipeline(s)

2022-08-03 12:25 UTC, pnadolny13 commented on data/extract/extractors.meltano.yml
> +      - CFFBG6DS4
@WayneBanksy do you have a mapping for these that you can share? I'm interested in what channels were choosing to consume from vs not consume. Its hard to tell from the IDs. No changes requested to the code, just for helping me review.


Optionally if you wanted you could put a comment next to each in the yaml file so its clear what were selecting now that we have a lot to keep track of. Something like:

```yaml
- CMN8HELB0 # getting-started
```

2022-08-03 12:29 UTC, pnadolny13 commented on data/transform/models/staging/slack/stg_slack_threads.sql
> +        {{ dbt_utrils.surrogate_key(
@WayneBanksy do we need the `message_surrogate_key` for this case? I believe in the messages stream we didnt receive a unique ID from the API so we had to combine a few fields to define uniqueness. But in the [users stream](https://github.com/meltano/squared/blob/a491f2b133ca7dd031a9556de99ea7f71c463285/data/transform/models/staging/slack/stg_slack__users.sql#L6) we get a unique user id we could use.

If we do need this generated column to have uniqueness, we should flow it through in the rest of the selects so its accessible in the final table. We can also put a schema test to confirm its always unique like https://github.com/meltano/squared/blob/a491f2b133ca7dd031a9556de99ea7f71c463285/data/transform/models/staging/slack/schema.yml#L6.

2022-08-03 12:33 UTC, pnadolny13 commented on data/transform/models/staging/slack/stg_slack_threads.sql
> +        channel_id,
@WayneBanksy it looks like some of these are inconsistently between implicit/explicit aliasing, I think sqlfluff will complain about that i.e. some are explicitly aliased using their original name while others are implicitly named, for examaple:

```
        files,
        is_locked AS is_locked,
```

`files` is implicitly aliased while `is_locked` is explictly aliased. Can you just take another quick pass over those?

2022-08-03 12:34 UTC, pnadolny13 requested changes
@WayneBanksy this looks great! Thanks for splitting up your PRs.

I left a few minor comments and questions. Feel free to respond if you want me to clarify anything.

2022-08-04 00:57 UTC, WayneBanksy commented on data/extract/extractors.meltano.yml
> +      - CFFBG6DS4
[slack_analysis_channel_names_ids.csv](https://github.com/meltano/squared/files/9255828/slack_analysis_channel_names_ids.csv)

I'll go ahead and take you up on your suggestion to comment out the names of the channels for easy reference. I've also attached the csv that has a list of the channels, their names, and the number of members in the channel. We made decisions using the following parameters:
- channel name: an indicator of whether questions may be asked there relevant to the questions we're attempting to answer
- number of members: higher numbers may be a validating indicator "of whether questions..." 

Looking forward to your thoughts.

2022-08-04 01:16 UTC, WayneBanksy commented on data/transform/models/staging/slack/stg_slack_threads.sql
> +        {{ dbt_utrils.surrogate_key(
For the [users stream](https://github.com/meltano/squared/blob/a491f2b133ca7dd031a9556de99ea7f71c463285/data/transform/models/staging/slack/stg_slack__users.sql#L6), is the unique key the `user_id`? 

To address: 
> do we need the message_surrogate_key for this case? 

I think(?) we do. The most unique identifier at the message level in the threads stream is the `ts` (alias `message_created_at`), which is similar to the messages stream. I've made the suggested update in the meantime.

2022-08-04 01:19 UTC, WayneBanksy commented on data/transform/models/staging/slack/stg_slack_threads.sql
> +        channel_id,
I was a bit confused by this using the [stg_slack__messages](https://github.com/meltano/squared/blob/a491f2b133ca7dd031a9556de99ea7f71c463285/data/transform/models/staging/slack/stg_slack__messages.sql#:~:text=display_as_bot%20AS%20display_as_bot,upload%20AS%20upload%2C) as my north star. What's the prescribed approach? I assumed there was a reason that I didn't have context for.

2022-08-05 13:07 UTC, pnadolny13 commented on data/transform/models/staging/slack/stg_slack_threads.sql
> +        channel_id,
@WayneBanksy yeah thats a good catch, I think https://github.com/meltano/squared/blob/a491f2b133ca7dd031a9556de99ea7f71c463285/data/transform/models/staging/slack/stg_slack__messages.sql is pretty inconsistent too. I would have expected SQLFluff to complain about that but maybe not. We can call this an "optional update" then.

Lets just go with the rule, "if we're not changing the original column name then no need to alias it".

2022-08-05 13:13 UTC, pnadolny13 commented on data/transform/models/staging/slack/stg_slack_threads.sql
> +        {{ dbt_utrils.surrogate_key(
@WayneBanksy I havent looked at the data coming out of the threads stream so I dont personally know the answer but it sounds like we will need a surrogate ID for sure. Is it a thread ID then or still a message ID? What components make it unique?

I'd go ahead and follow the suggestion I made in the other comment, the dbt tests will fail if its not unique so we'll know:

>If we do need this generated column to have uniqueness, we should flow it through in the rest of the selects so its accessible in the final table. We can also put a schema test to confirm its always unique like

2022-08-05 13:37 UTC, pnadolny13 commented on data/extract/extractors.meltano.yml
> +      - CFFBG6DS4
@WayneBanksy I know you all built your work with this subset of public channels but thinking more holistically about the data we want to pull from slack, for other analysis besides this one, it might be better to pull in all public channels then filter for your subset in your downstream models. Also this configuration is set to only pull private channels and it looks like we can only set  1 [channel type](https://hub.meltano.com/extractors/tap-slack--meltanolabs#channel-types) per sync so you'll have to use the `inherits_from` [feature](https://docs.meltano.com/concepts/project#inheriting-plugin-definitions) here to have 2 separate tap configurations. See [tap-github](https://github.com/meltano/squared/blob/c967fe2932d7dc4611660efd324d1567ef08a936/data/extract/extractors.meltano.yml#L75)/tap-github-meltano/tap-github-search for an example. This is what I'd suggest: 

3 tap configurations mimicking the pattern from the tap-github configs:
1. a base `tap-slack`
2. `tap-slack-private` with the configs that currently exist today for the private channel type and channel C01SK13R9NJ
3. `tap-slack-public` with no list of included channels so all public channels are included maybe using [excluded_channels](https://hub.meltano.com/extractors/tap-slack--meltanolabs#excluded-channels) for some non-work channels if necessary due to long sync times but starting with no exclusions would be best.

We wouldnt end up calling the base tap-slack ever, only tap-slack-private/public.

@tayloramurphy do you think we should try pulling all private channels for any reason? Do you think we should include/exclude non-work channels like bookclub and motorsports?

2022-08-05 14:12 UTC, tayloramurphy commented on data/extract/extractors.meltano.yml
> +      - CFFBG6DS4
@pnadolny13 I don't think we need to pull private channels right now. There's no compelling use case and it doesn't feel quite right.

2022-08-05 18:48 UTC, pnadolny13 commented on data/extract/extractors.meltano.yml
> +      - CFFBG6DS4
@tayloramurphy sounds good, although the one channel we pull as of today is the private `new-members-notice` channel. I'm understanding your last message as "dont pull all private channels" and "dont do the work to pull any new ones since they arent needed".

Let me know if thats not what you meant 😄

2022-08-05 20:06 UTC, tayloramurphy commented on data/extract/extractors.meltano.yml
> +      - CFFBG6DS4
@pnadolny13 that's a good read 😄

2022-08-16 22:54 UTC, WayneBanksy commented on data/extract/extractors.meltano.yml
> +      - CFFBG6DS4
@pnadolny13 Let's check in on this as I mentioned in slack. I'll post an update here if I make any additional progress with this configuration for `tap-slack`.

2022-09-14 18:31 UTC, pnadolny13 commented
@WayneBanksy  if this PR isn't relevant anymore, would you mind closing it?

2022-09-16 17:38 UTC, pnadolny13 commented
Closing since I dont think this is relevant anymore, feel free to reopen if I'm wrong about that.

2022-09-16 17:38 UTC, closed without merging