feat: Add encrypted `.env` creds
meltano/squared pull request #475
Opened 2022-11-07 16:34 UTC by kgpayne

Closes #463

- #463

2022-11-07 16:44 UTC, kgpayne commented
@aaronsteers I have tested this with a publickey from the sandbox account and, as expected, our Google Analytics credentials are too long to fit into one ciphertext. I have created [this issue](https://github.com/meltano/kms-ext/issues/1) to track chunking long plaintext into arrays of ciphertexts in `secrets.yml`, but we need not necessarily block on it.

2022-11-08 17:00 UTC, magreenbaum commented
> How to deliver the public key (.pem file or similar) to the project owner. @magreenbaum - any thoughts on this?

Maybe a `meltano` command that downloads it. I would just need to add `kms:GetPublicKey` permissions for the container. https://docs.aws.amazon.com/kms/latest/APIReference/API_GetPublicKey.html

> Even if using a short-term approach, can we get Ken a public key for the squared project today or tomorrow? 

Is this needed in the sandbox account or somewhere else?

2022-11-08 19:55 UTC, magreenbaum commented
> Even if using a short-term approach, can we get Ken a public key for the squared project today or tomorrow? 

We can manually generate a KMS key for now or we can deploy the infra off https://github.com/meltano/dragon-infra/pull/91 and see how it goes in the new staging account. Right now nothing is deployed in staging.

2022-11-15 19:15 UTC, pnadolny13 approved these changes
@kgpayne this looks great!

As a side not since I'm curious - are we expecting to have one of these secrets.yml files for each meltano environment? It would be really helpful in CI to just pull secrets from KMS vs storing them in GitHubs secret store. Having a `secrets` key attached to each meltano env seems super useful, each slightly different than each other.

2022-11-15 19:15 UTC, pnadolny13 commented on data/environments/userdev.meltano.yml
> +    # Secrets via KMS
@kgpayne are these env variables required in the other meltano environments (cicd/staging/prod) as well?

2022-11-15 19:21 UTC, WillDaSilva requested changes

2022-11-15 19:21 UTC, WillDaSilva commented on data/secrets.yml
> +env:
- https://github.com/meltano/kms-ext/pull/2

```suggestion
kms_key_id: 17dcca7a-39d3-46b1-b2b3-83fcc2375747
env:
```

This will help quickly address this issue:
- https://github.com/meltano/infra/issues/140

2022-11-15 19:40 UTC, pnadolny13 commented
>@aaronsteers I have tested this with a publickey from the sandbox account and, as expected, our Google Analytics credentials are too long to fit into one ciphertext. I have created https://github.com/meltano/kms-ext/issues/1 to track chunking long plaintext into arrays of ciphertexts in secrets.yml, but we need not necessarily block on it.

@kgpayne I'm not sure what the size limit is exactly but fwiw we could split the TAP_GOOGLE_ANALYTICS_CLIENT_SECRETS secret into its parts using the dot syntax so they live in the meltano.yml file since most of them arent sensitive, like:

```
      client_secrets:
        type: service_account
        token_uri: https://oauth2.googleapis.com/token
```

and only leave the truly secret sections like `private_key` and `private_key_id`? The private key in that GA credentials json is almost 1800 characters in itself so thats mostly the problem.

2022-11-16 19:22 UTC, WillDaSilva approved these changes

2022-11-16 19:34 UTC, aaronsteers commented
https://github.com/meltano/squared/actions/runs/3482409891/jobs/5824784907

```log
2022-11-16T19:28:26.430364Z [info     ] 19:28:26  Database Error in test source_unique_tap_spreadsheets_anywhere_azure_ips_id (snapshots/spreadsheets_anywhere/sources.yml) cmd_type=command name=dbt-snowflake stdio=stderr
2022-11-16T19:28:26.431071Z [info     ] 19:28:26    002003 (42S02): SQL compilation error: cmd_type=command name=dbt-snowflake stdio=stderr
2022-11-16T19:28:26.431896Z [info     ] 19:28:26    Object 'CICD_RAW.BFBC13D0FB1F7549736BC8FFF3A544484D893C035_TAP_SPREADSHEETS_ANYWHERE.AZURE_IPS' does not exist or not authorized. cmd_type=command name=dbt-snowflake stdio=stderr
```

2022-11-16 21:39 UTC, pnadolny13 commented
@aaronsteers related to the failing test I created https://github.com/meltano/squared/pull/480 that should fix it, once thats pulled in this PR should pass. Optionally since this is hi priority we can force merge since this PR doesnt affect anything thats being tested anyways.

https://github.com/meltano/squared/issues/354 is the actual issue that periodically causes the test to fail since we dont have a way to dynamically generate the url yet.

2022-11-16 21:57 UTC, merged